# Generated by Django 3.0.5 on 2021-12-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Feature_name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('in_stock', models.BooleanField(default=True, verbose_name='In Stock')),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
                ('category', models.ManyToManyField(blank=True, to='graphqlapp.Category', verbose_name='Product categories')),
            ],
        ),
    ]
