# Generated by Django 3.0.5 on 2021-12-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date created'),
        ),
    ]
